SAMPLE_POSTS = [
    {
        "raw_text": "היי כולם, מפתח React עם 4 שנות ניסיון. עובד בסטארטאפ סדרה B בתל אביב. קיבלתי הצעה של 28K. נשמע הגיוני?",
        "role": "Frontend Developer",
        "years_experience": 4,
        "salary": 28000,
        "company_stage": "Series B",
        "location": "תל אביב",
        "source": "facebook",
    },
    {
        "raw_text": "עדכון שכר לקהילה: DevOps עם 6 שנים, חברה פיננסית גדולה, מרכז. 42K + בונוס שנתי. שוק מאוד חזק כרגע.",
        "role": "DevOps",
        "years_experience": 6,
        "salary": 42000,
        "company_stage": "Enterprise",
        "location": "מרכז",
        "source": "facebook",
    },
    {
        "raw_text": "Team Lead בחברת פינטק, 8 שנות ניסיון, 3 שנים ניהול. מקבל 55K כולל רכב. תל אביב.",
        "role": "Team Lead",
        "years_experience": 8,
        "salary": 55000,
        "company_stage": "Fintech",
        "location": "תל אביב",
        "source": "facebook",
    },
    {
        "raw_text": "Data Scientist ג׳וניור, שנה וחצי ניסיון, חברת SaaS. מציעים לי 22K. זה בסדר לג׳וניור?",
        "role": "Data Scientist",
        "years_experience": 1.5,
        "salary": 22000,
        "company_stage": "SaaS",
        "location": "תל אביב",
        "source": "facebook",
    },
    {
        "raw_text": "Backend Python, 5 שנים, חברת אינטרנט בינונית, רמת גן. 34K. עוברים ל-FastAPI, מאוד מרוצה מהסביבה.",
        "role": "Backend Developer",
        "years_experience": 5,
        "salary": 34000,
        "company_stage": "Growth",
        "location": "רמת גן",
        "source": "facebook",
    },
]
